recipe: default.v1
language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 120
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 120
policies:
- name: RulePolicy
assistant_id: 20260406-194224-concave-stockade
